name: Install Apache2

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch

jobs:
  install-apache2:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package list
        run: sudo apt-get update

      - name: Install Apache2
        run: sudo apt-get install -y apache2

      - name: Check Apache2 version
        run: apache2 -v

      - name: Start Apache2 service
        run: sudo systemctl start apache2

      - name: Verify Apache2 status
        run: sudo systemctl status apache2
